# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

DOTFILES=$HOME/.dotfiles
DOTFILES_SHELL=$DOTFILES/src/shell
ZSH=$DOTFILES_SHELL/oh-my-zsh
ZSH_THEME="powerlevel10k/powerlevel10k"
ZSH_CUSTOM=$DOTFILES_SHELL/zsh

# Source custom functions
source $DOTFILES_SHELL/zsh/functions/*.zsh

# Plugins list
plugins=(zsh-completions zsh-autosuggestions zsh-better-npm-completion zsh-syntax-highlighting zsh-nvm history-substring-search jsontools sudo urltools web-search git node npm vscode yarn)

# Setup plugin `history-substring-search`
zmodload zsh/terminfo
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down

# Source Oh My Zsh
source $ZSH/oh-my-zsh.sh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
